### ISSUE TITLE
Async example

### ISSUE THREAD

**Issue by AlexisQapa** [natario1/Autocomplete#15]
Hi, I'm having trouble to get it working with async load of autocompletions. 

I think it would be nice if you could provide an example of an async Presenter with a progress / failure management. This join the request from #12

**Comment by natario1** [comment]
This is not an Autocomplete issue but standard `RecyclerView` management.

If you can show a progress in your activity `RecyclerView`, than you can show it with Autocomplete. Autocomplete will just present what you give.

For example (just one of the many ways) your adapter can return 1 for getItemCount() while loading, and display a loading indicator there.

**Comment by AlexisQapa** [comment]
My issue is not really about UI but more about async management linked to the adapter update and popup showing dismissing. I'm still investigating an I'll try to build a minimal example.

Here is my main issue : 
My repository send first an empty list while loading then the actual list. Items arrive in order but as soon as the recycler is populated with the second list the dialog is dismissed (data is shown for like 100ms)
My configuration is close to the one in the sample.

**Comment by natario1** [comment]
Are you using the RecyclerViewPresenter or your own?

**Comment by AlexisQapa** [comment]
For now I'm using RecyclerViewPresenter, but I might write my own to customise it after I get the minimal behaviour working

**Comment by natario1** [comment]
I understand your problem, I think it was introduced in 1.0.3.

We dismiss the popup if height == 0. So right now you should provide a 'loading' item of some sort, or add some padding to the recyclerView. Anything that might give the view some height.

**Comment by AlexisQapa** [comment]
Hahah spent the day on this one .. got it working with 1.0.2. 
Gonna try with a more complex layout that should not be empty. Thanks !

**Comment by natario1** [comment]
Maybe it can be fixed on our side, I'll take a look

**Comment by natario1** [comment]
Not able to solve this easily. We should introduce a 'loading state' and it takes some work.
For now I have bumped version to 1.1.0 since the change was more breaking than I thought.

I have stated more clearly in README that height == 0 means that the popup will be dismissed.
