### ISSUE TITLE
How can I use the cursor as anchor istead of the view?

### ISSUE THREAD

**Issue by danielnazareth-hotmart** [natario1/Autocomplete#17]
When the EditText is too big, the popup is not shown properly, as you can see here:

![2888403606721068496](https://user-images.githubusercontent.com/22893561/39007060-493c572e-43db-11e8-89e4-0e998a6a163b.png)

Is there any way that I can use the cursor as the anchor? And one more doubt, can I choose if the popup will be shown above or below the anchor in some situations?

**Comment by natario1** [comment]
It's not possible right now, but it would be a cool feature!
