### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by mansya** [natario1/Autocomplete#18]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by natario1** [comment]
Feel free to do it! We could use it as the sample app icon

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you l like it ?

![autocomplete](https://user-images.githubusercontent.com/33461607/43456661-8e9d8c3e-94ee-11e8-835d-2ae017a9ff2e.png)

**Comment by mansya** [comment]
You can tell me if you want to change the color.

**Comment by mansya** [comment]
how about the logo. I really hope for a positive response from you.
