### ISSUE TITLE
How to show popup always above the EditText

### ISSUE THREAD

**Issue by akashrao1991** [natario1/Autocomplete#19]
I have an editText in the middle of the screen. I want to show the popup always above the editText. How to achieve it?
I have tried setting the height of the popup as larger than the bottom remaining space.This always does the trick.I want the height to wrap content and always remain above the editText.

Thanks.
Akash Rao

**Comment by natario1** [comment]
You can't at the moment

**Comment by flypikadev** [comment]
@akashrao1991 @natario1 hi any news? can i do it now?

**Comment by akashrao1991** [comment]
Don't know .. haven't tried it in a while.I'll try and let you know
