### ISSUE TITLE
Need a sample app

### ISSUE THREAD

**Issue by aparcero** [natario1/Autocomplete#2]
I've having trouble trying to use the library, even with the current documentation. A sample app 
with examples similar to the ones shown on the animation would be nice

**Comment by natario1** [comment]
I agree, I’ll work on a sample app as soon as I can. Meanwhile if you have specific questions about the APIs, feel free to ask

**Comment by natario1** [comment]
Small sample app is available in the `/sample` module. I am planning to add more so I’ll leave this open. Let  me know if you have troubles.

**Comment by aparcero** [comment]
Thanks, I'll check it out
