### ISSUE TITLE
onSocialTextChanged is not working on OnePlus phones

### ISSUE THREAD

**Issue by sswara28** [natario1/Autocomplete#20]
Hashtags not getting autoCompleted  on onePlus phones.
Control doesnt go to onSocialTextChanged method when we change a text in  SocialAutoCompleteTextView.

**Comment by natario1** [comment]
Sorry to hear but probably you posted this issue to the wrong library.

**Comment by serkanucar** [comment]
I have the same problem hashtag and mention.
I sent the screenshot video to your email address.
It's not only on onePlus phones. (I use Samsung a50)
