### ISSUE TITLE
AutocompletePopup does not respect "windowSoftInputMode:adjustResize" in API level 26

### ISSUE THREAD

**Issue by varun-devappsys** [natario1/Autocomplete#22]
When the softkeyboard shows popup doesnt pan/resize along with the keyboard thus hiding the edittext

**Comment by natario1** [comment]
I don't know how to do it myself. The Autocomplete class exposes some 'inputMode' methods, so feel free to play with them and see if you manage to get it working. I couldn't. Related:

https://stackoverflow.com/q/7417123/4288782
https://issuetracker.google.com/issues/36911528

In another app I am using, I use `adjustResize` in the manifest, and I use this class as the **root element of the activity**:

```kotlin
class RootCoordinatorLayout @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0)
    : CoordinatorLayout(context, attrs, defStyleAttr) {

    init {
        ViewCompat.setOnApplyWindowInsetsListener(this) { view, inset ->
            view.setPadding(0, 0, 0, inset.systemWindowInsetBottom)
            inset.replaceSystemWindowInsets(inset.systemWindowInsetLeft,
                    inset.systemWindowInsetTop, inset.systemWindowInsetRight, 0)
        }
    }
}
```

This way it works well.
