### ISSUE TITLE
Help creating custom AutocompletePolicy

### ISSUE THREAD

**Issue by jahirfiquitiva** [natario1/Autocomplete#25]
Hello

I am trying to create a custom policy where the popup appears after a keyword is typed in the `EditText`

Here's my current solution, but it isn't working 😕. Could you please check and tell me what's wrong with it? 🙏 

```java
public class KeywordPolicy implements AutocompletePolicy {
    @Override
    public boolean shouldShowPopup(Spannable text, int cursorPos) {
        return text.toString().startsWith("key");
    }

    @Override
    public boolean shouldDismissPopup(Spannable text, int cursorPos) {
        return text.toString().length() <= 0;
    }

    @Override
    public CharSequence getQuery(Spannable text) {
        return text.toString();
    }

    @Override
    public void onDismiss(Spannable text) {
    }
}
```

**Comment by natario1** [comment]
What is not working?

**Comment by jahirfiquitiva** [comment]
@natario1  I type `key` as it's the keyword, and the autocomplete popup just doesn't appear

**Comment by natario1** [comment]
Ah, then I don't know, it should work. Try with the default policy or CharPolicy and see if it works, you might have a different issue
