### ISSUE TITLE
Want to delete @mentioned user name on edit text

### ISSUE THREAD

**Issue by Abhilash1307** [natario1/Autocomplete#26]
Hello your view is working very fine.but my issue is if i mentioned multiple user. if i delete any character from particular mentioned user name then it should delete all that user name

**Comment by natario1** [comment]
I suggest asking this on StackOverflow.

**Comment by Abhilash1307** [comment]
I have searched for this but they are not giving me answer that i can use  some one is saying use spyglass library this library has implemented delete related functionality. but by using that library i have no control over my data i was unable to get which value is clicked

**Comment by natario1** [comment]
This has nothing to do with the library, you just need a TextWatcher to delete stuff, in addition to Autocomplete. I am sure someone at SO can help you 👍
