### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by eakteam** [natario1/Autocomplete#29]
Will be there any update of this good library ?

**Comment by natario1** [comment]
I will maintain this library but I don't see any new feature coming, this already does its job.

**Comment by eakteam** [comment]
I agree with that, but it will be awesome to update to the latest Android SDK (28) and migrate to Androidx libraries. In following Play Store will require to use latest SDK and old Support Library is no more supported, they go to Androidx.

Optional : 
This is optional but i think that is better to migrate to Kotlin too.

Best Regards and thanks for this great helpful lib ! :)

**Comment by eakteam** [comment]
Android Q has been relesed. And except build tools version & sdk, many things need to be improved and updated. 
Thanks for this lib, great work
