### ISSUE TITLE
Bug when call popupWindow.showAsDropDown() on API 24.

### ISSUE THREAD

**Issue by zedocpt** [natario1/Autocomplete#3]
Hello,

On your AutocompletePopup class, on line 376, when you call popupWindow.showAsDropDown() funcion, 
the is a bug on Api 24, you should replace the current line to :

``
// API 24 PopupWindow bug fix

        if (Build.VERSION.SDK_INT == Build.VERSION_CODES.N) {
            int[] a = new int[2];
           getAnchorView().getLocationInWindow(a);
            popupWindow.showAtLocation(context.getWindow().getDecorView(), Gravity.NO_GRAVITY, a[0], a[1] + anchorView.getHeight());

        } else {
            popupWindow.showAsDropDown(getAnchorView());
        }
``

Best regards
José Martins

**Comment by natario1** [comment]
Hi, thanks for the feedback. I have some questions,

- N is API 25. Do you mean M?
- why ==? Should it be >=? Or only on one API level?
- why do you think this should be changed? What is the issue you are seeing?

**Comment by zedocpt** [comment]
hi again, 

Please check this link https://stackoverflow.com/questions/39673099/android-nougat-popupwindow-showasdropdown-gravity-not-working

Best regards
José Martins
