### ISSUE TITLE
Close popup

### ISSUE THREAD

**Issue by cadelisme** [natario1/Autocomplete#31]
when the value is empty or null, I hope the popup will  disappear.

In your sample when isEmpty inside public void onBindViewHolder. I want to close the popup. How to do it? please help me. many thanks :)

**Comment by Pirokar** [comment]
```
autocomplete = Autocomplete.on<EditText>(notesMessageInput.inputEditText)
                .with(CharPolicy('@'))
                .with(AutocompleteMentionPresenter(presenter))
                .build()

autocomplete?.dismissPopup()
```
