### ISSUE TITLE
Change width of the dropdown dialog

### ISSUE THREAD

**Issue by BRoy98** [natario1/Autocomplete#4]
I added an email field on the drop-down. When the email is too long, it goes to the 2nd line with is not totally visible. Is it possible to make the drop-down dialog width wrap-content so that it can show it in one line only and increase the width as required?

**Comment by natario1** [comment]
It's all about what you return in getPopupDimensions , are you overriding that?

If you want the text field in one line, try adding android:max_lines="1" to the text view

**Comment by BRoy98** [comment]
getPopupDimensions helped me! 😃
