### ISSUE TITLE
Sample app crashes on orientation change

### ISSUE THREAD

**Issue by Shalom** [natario1/Autocomplete#5]
FYI, the sample app crash when starting to type at the "Look for a single user" field and rotating the device while the popup is visible.

> 12-21 13:59:33.173 31972-31972/com.otaliastudios.sample E/AndroidRuntime: FATAL EXCEPTION: main
>   Process: com.otaliastudios.sample, PID: 31972
>   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.otaliastudios.sample/com.otaliastudios.sample.MainActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
>       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
>       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
>       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
>       at android.app.ActivityThread.-wrap18(Unknown Source:0)
>       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
>       at android.os.Handler.dispatchMessage(Handler.java:106)
>       at android.os.Looper.loop(Looper.java:164)
>       at android.app.ActivityThread.main(ActivityThread.java:6494)
>       at java.lang.reflect.Method.invoke(Native Method)
>       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
>    Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
>       at android.view.ViewRootImpl.setView(ViewRootImpl.java:765)
>       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
>       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
>       at android.widget.PopupWindow.invokePopup(PopupWindow.java:1433)
>       at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1284)
>       at android.support.v4.widget.PopupWindowCompat$PopupWindowCompatApi19Impl.showAsDropDown(PopupWindowCompat.java:114)
>       at android.support.v4.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:218)
>       at com.otaliastudios.autocomplete.AutocompletePopup.show(AutocompletePopup.java:376)
>       at com.otaliastudios.autocomplete.Autocomplete.showPopup(Autocomplete.java:232)
>       at com.otaliastudios.autocomplete.Autocomplete.onTextChanged(Autocomplete.java:337)
>       at android.widget.TextView.sendOnTextChanged(TextView.java:9364)
>       at android.widget.TextView.setText(TextView.java:5397)
>       at android.widget.TextView.setText(TextView.java:5250)
>       at android.widget.EditText.setText(EditText.java:113)
>       at android.widget.TextView.setText(TextView.java:5207)
>       at android.widget.TextView.onRestoreInstanceState(TextView.java:5082)
>       at android.view.View.dispatchRestoreInstanceState(View.java:17706)
>       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
>       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
>       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
>       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
>       at android.view.View.restoreHierarchyState(View.java:17684)
>       at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2131)
>       at android.app.Activity.onRestoreInstanceState(Activity.java:1102)
>       at android.app.Activity.performRestoreInstanceState(Activity.java:1057)
>       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1260)
>       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
>       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
>       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699) 
>       at android.app.ActivityThread.-wrap18(Unknown Source:0) 
>       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
>       at android.os.Handler.dispatchMessage(Handler.java:106) 
>       at android.os.Looper.loop(Looper.java:164) 
>       at android.app.ActivityThread.main(ActivityThread.java:6494) 
>       at java.lang.reflect.Method.invoke(Native Method) 
>       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
>       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by AlexisQapa** [comment]
This bug is still occurring with the latest version (1.0.3) on the example app. I can't find a way to handle it in my app even with 
```
override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        autoComplete.setEnabled(true)
}

override fun onDetachedFromWindow() {
        autoComplete.dismissPopup()
        autoComplete.setEnabled(false)
        super.onDetachedFromWindow()
}
```

**Comment by AlexisQapa** [comment]
Just checking if windows is attached before showing the popup is sufficient to avoid the crash :
`public static class SimplePolicy implements AutocompletePolicy {
        @Override
        public boolean shouldShowPopup(Spannable text, int cursorPos) {
            return text.length() > 0 && ViewCompat.isAttachedToWindow(edittext);
        }
}`

Thought this should be done at the library level and this is only avoid the crash, the issue is that the popup is kept when it should not.

**Comment by natario1** [comment]
Thanks for looking at this @AlexisQapa .

So `shouldShowPopup` is triggered on the destroyed activity while it is being destroyed, and if it returns true, we create an invalid popup in the old activity. Right?

I see two solutions -

- Modify the `Autocomplete` class so it removes itself as a listener from the EditText when the EditText is detached from window. Should use `View.OnAttachStateChangeListener`. Can be tricky.
- Modify the `AutocompletePopup` so it checks for `view.isAttachedToWindow()` before creating a popup.

The first can be tricky, the second is just one line and I think would be a better solution.

**Comment by AlexisQapa** [comment]
The second option would be simpler but edit text might end up with large number of text watchers if it's never removed.

**Comment by natario1** [comment]
I went for the second for now, I don't have much time. Anyway when you destroy the activity and recreate everything is released, you get a new EditText.
