### ISSUE TITLE
Is it possible to add Autocomplete entries on the go?

### ISSUE THREAD

**Issue by EnriqueSoria** [natario1/Autocomplete#8]
I'm working on an app where users have to put people names on it. I want to let them put one of the suggested by autocompletion, but let them put names that aren't suggested. And, in this case, add this new name to the suggestion list.

Is that possible? I didn't manage myself to do it.

Thanks in advance! 

Edit: It's in fact possible, putting an ArrayList inside `RecyclerViewPresenter`.

**Comment by iwebnetid** [comment]
cannot make 2 Autocomplete in one class ?
ive tried it but error on with(presenter) and with(callback)
